### PR TITLE
update runtime 23.08 and add zh_CN app name

### PR DESCRIPTION
**Pull request by pugaizai**

### CODE REVIEW

**Comment by pugaizai** [comment]
@wsgalaxy  please merge

**Comment by pugaizai** [comment]
bot,build

**Comment by pugaizai** [comment]
bot, build

**Comment by zhiiwg** [comment]
@madoka773 any update for runtime 23.08?

**Comment by pugaizai** [comment]
> @madoka773 any update for runtime 23.08?

im not the maintainer of the repo. i dont have the permission to make a commit

**Comment by zhiiwg** [comment]
> > @madoka773 any update for runtime 23.08?
> 
> im not the maintainer of the repo. i dont have the permission to make a commit

Can you open this pr again? (if the update has no problem), and @wsgalaxy can you merge it for a new release of qqmusic?🙏

**Pull request closed without merging**
